import { saveComment } from "@/core/github";
import { getCommentBody } from "./get-comment-body";

/** Stable marker used to find and update the README validation pull-request comment. */
export const README_COMMENT_IDENTIFIER = "<!-- readme-comment -->";

/**
 * Posts or updates the pull-request comment generated by the README validator.
 *
 * @returns A promise that resolves after the comment has been persisted.
 * @throws {Error} When GitHub workflow metadata or the comment request fails.
 * @example
 * ```ts
 * await postReadmeComment();
 * ```
 */
export async function postReadmeComment() {
  const content = await getCommentBody();

  await saveComment({
    body: `${content}`,
    identifier: README_COMMENT_IDENTIFIER,
  });

  console.log("[Readme Reporter] Comment processed successfully.");
}
