import { getCommentWithId, saveComment } from "@/core/github";
import { getCommentBody } from "./get-comment-body";

/** Stable marker used to find and update the README validation pull-request comment. */
export const README_COMMENT_IDENTIFIER = "<!-- readme-comment -->";

/**
 * Posts or updates the pull-request comment generated by the README validator.
 *
 * @returns A promise that resolves after the comment has been persisted.
 * @throws {Error} When GitHub workflow metadata or the comment request fails.
 * @example
 * ```ts
 * await postReadmeComment();
 * ```
 */
export async function postReadmeComment() {
  const [content, comment] = await Promise.all([
    getCommentBody(),
    getCommentWithId(README_COMMENT_IDENTIFIER),
  ]);

  console.log(
    comment
      ? `[Readme Reporter] Updating existing PR comment ID: ${comment.id}`
      : "[Readme Reporter] Posting new PR comment...",
  );

  await saveComment({
    body: `${content}`,
    id: comment?.id ?? null,
    identifier: README_COMMENT_IDENTIFIER,
  });

  console.log("[Readme Reporter] Comment processed successfully.");
}
